# Generated by Django 5.1.6 on 2025-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_comment_commenter_ip_comment_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter_ip',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_anonymous',
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
